package com.loanguard.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

/**
 * Financial education knowledge base entry.
 * Used by Atlas Vector Search for semantic retrieval in the AI assistant.
 * Embedding is generated by Gemini text-embedding-004 (768 dimensions).
 */
@Document(collection = "knowledge")
public class KnowledgeEntry {

    @Id
    private String id;

    private String title;
    private String category;        // e.g. LOAN_EDUCATION, RISK_FACTOR, FINANCIAL_PLANNING
    private String content;
    private List<Double> embedding; // 768-dim vector from text-embedding-004

    public String getId()                        { return id; }
    public void setId(String v)                  { this.id = v; }
    public String getTitle()                     { return title; }
    public void setTitle(String v)               { this.title = v; }
    public String getCategory()                  { return category; }
    public void setCategory(String v)            { this.category = v; }
    public String getContent()                   { return content; }
    public void setContent(String v)             { this.content = v; }
    public List<Double> getEmbedding()           { return embedding; }
    public void setEmbedding(List<Double> v)     { this.embedding = v; }
}
